# Generated by Django 3.2 on 2021-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Título')),
                ('capital', models.CharField(max_length=200, verbose_name='Título')),
                ('main_picture', models.ImageField(upload_to='Articles/', verbose_name='Foto de portada')),
                ('short_description', models.CharField(default='Debes cambiarme eh!', max_length=300, verbose_name='Descripción')),
            ],
        ),
    ]
