# Generated by Django 3.2 on 2021-06-19 15:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20210605_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Contenido'),
        ),
    ]
