# Generated by Django 3.2 on 2021-06-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
